# This is a basic workflow to help you get started with Actions

name: start-wf

# Controls when the action will run. 
on:  
  schedule:
    - cron: '0 6 * * *' 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: CF CLI Action
        uses: citizen-of-planet-earth/cf-cli-action@v1
        with:
          # Target API Endpoint of Cloud Foundry
          cf_api: https://api.cf.eu10.hana.ondemand.com
          # Username for API authentication
          cf_username: ${{ secrets.SCP_USER }}
          # Password for API authentication
          cf_password: ${{ secrets.SCP_PASSWORD }}
          # Target Organization
          cf_org: ${{ secrets.SCP_ORG }}
          cf_space: dev
          command: start WorkflowManagementFLP_appRouter
